# Generated by Django 3.2.5 on 2021-07-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0010_auto_20210720_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejob',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
